sudo: required
services:
  - docker

before_install:
  - docker build -t sus-evo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sus-evo/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-295332586563"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

    
